# Generated by Django 3.1.2 on 2020-11-03 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_ca',
            field=models.TextField(null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_es',
            field=models.TextField(null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_fr',
            field=models.TextField(null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ca',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
