# Generated by Django 3.1.2 on 2020-11-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20201106_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug_ca',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug_es',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Page URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug_fr',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Page URL'),
        ),
    ]
